<?php



/**
 * This class defines the structure of the 'sf_simple_cms_slot' table.
 *
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Jan 25 07:28:17 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.zeroSimpleCMSPlugin.lib.model.map
 */
class sfSimpleCMSSlotTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.zeroSimpleCMSPlugin.lib.model.map.sfSimpleCMSSlotTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_simple_cms_slot');
		$this->setPhpName('sfSimpleCMSSlot');
		$this->setClassname('sfSimpleCMSSlot');
		$this->setPackage('plugins.zeroSimpleCMSPlugin.lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('PAGE_ID', 'PageId', 'INTEGER' , 'sf_simple_cms_page', 'ID', true, null, null);
		$this->addPrimaryKey('CULTURE', 'Culture', 'VARCHAR', true, 7, null);
		$this->addPrimaryKey('NAME', 'Name', 'VARCHAR', true, 100, null);
		$this->addColumn('TYPE', 'Type', 'VARCHAR', true, 100, 'Text');
		$this->addColumn('VALUE', 'Value', 'LONGVARCHAR', false, null, null);
		$this->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfSimpleCMSPage', 'sfSimpleCMSPage', RelationMap::MANY_TO_ONE, array('page_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'soft_delete' => array('deleted_column' => 'deleted_at', ),
			'timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // sfSimpleCMSSlotTableMap
