## YAML Template.
---
generator:
  class: sfPropelGenerator
  param:
    model_class:           sfSimpleCMSPage
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              sfSimpleCMSPage
    plural:                sfSimpleCMSPages
    route_prefix:          sf_simple_cms_page
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
