<?php

/**
 * Skeleton subclass for performing query and update operations on the 'sf_simple_cms_page' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Sun Dec 26 19:51:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.zeroSimpleCMSPlugin.lib.model
 */
class sfSimpleCMSPageQuery extends BasesfSimpleCMSPageQuery
{

	public function slug($slug)
	{
		return $this->filterBySlug($slug, Criteria::EQUAL);
	}

	public function published($published = true)
	{
		return $this->filterByIsPublished($published);
	}

}

// sfSimpleCMSPageQuery
