<?php



/**
 * Skeleton subclass for representing a row from the 'sf_simple_cms_slot_archive' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.2-dev on:
 *
 * Thu Feb 19 21:23:51 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.zeroSimpleCmsPlugin.lib.model
 */
class SfSimpleCmsSlotArchive extends BaseSfSimpleCmsSlotArchive
{
}
