<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_simple_cms_page_archive' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.2-dev on:
 *
 * Thu Feb 19 21:23:51 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.zeroSimpleCmsPlugin.lib.model
 */
class SfSimpleCmsPageArchivePeer extends BaseSfSimpleCmsPageArchivePeer
{
}
